[workspace]

members = [
    "atmega328p",
    "uno",
    "utils",
    "example/blinky-gpio-direct",
    "example/blinky-dpin-uno",
    "example/blinky-led-uno",
    "example/hello-usart-direct",
    "example/echo-usart-direct",
]

[profile.release]
lto = true